### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by gusanmaz** [trzy/llava-cpp-server#1]
I am able to run llava-cpp-server on CPU without an issue. Is there a way to run llava-cpp-server on GPU?

**Comment by trzy** [comment]
I believe llama.cpp has some CUDA support. I include llama.cpp as a sub repo so I would recommend looking at their docs to see whether this is true and if so, whether any build flags need to be enabled.

**Comment by yy9568** [comment]
> I am able to run llava-cpp-server on CPU without an issue. Is there a way to run llava-cpp-server on GPU?

Hi gusanmaz, what speed can you run on cpu?
