### ISSUE TITLE
whe I give non-existant file names, it segfaults

### ISSUE THREAD

**Issue by dataf3l** [trzy/llava-cpp-server#3]
these files do not exist:

models/*

I get this error

```
➜  llava-cpp-server git:(main) ./bin/llava-server -m ./models/ggml-model-q5_k.gguf --mmproj ./models/mmproj-model-f16.gguf
[1]    57986 segmentation fault  ./bin/llava-server -m ./models/ggml-model-q5_k.gguf --mmproj
```

what I kinda expected:
"sorry this file doesn't exist"

thanks in advance

**Comment by trzy** [comment]
Great catch but this is actually a problem with llama.cpp itself, which handles command line parsing and model file loading. That is, if you go into llama.cpp/ (or clone that repo independently and build it), and run ./llava with nonexistant filenames, the same segfault occurs. I want to refrain from reaching inside of llama.cpp but this would be a good issue to file with them directly.

**Comment by dataf3l** [comment]
@trzy https://github.com/ggerganov/llama.cpp/issues/3663
