### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by intulint** [trzy/llava-cpp-server#4]
make[2]: Leaving directory 'C:/neuro/llava-cpp-server/llama.cpp'
g++ -Illama.cpp -Illama.cpp/common -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move  -Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native  -o bin/llava-server   -Wno-cast-qual -DCPPHTTPLIB_ZLIB_SUPPORT -lz obj/llava_server.o obj/web_server.o llama.cpp/ggml.o llama.cpp/llama.o obj/clip.o llama.cpp/common.o llama.cpp/sampling.o llama.cpp/k_quants.o llama.cpp/ggml-alloc.o llama.cpp/ggml-backend.o
C:/neuro/w64devkit/bin/ld.exe: cannot find -lz: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.inc:62: bin/llava-server] Error 1
make[1]: Leaving directory 'C:/neuro/llava-cpp-server'
make: *** [Makefile:10: all] Error 2
C:/neuro/llava-cpp-server $

Windows 10, built using the tool w64devkit-fortran-1.20.0, with make command in project folder

**Comment by trzy** [comment]
No zlib? Are you using an environment like MinGW? Make sure zlib is installed (surprised it isn't). You can also try to remove CPPHTTPLIB_ZLIB_SUPPORT from the Makefile.

**Comment by cgisky1980** [comment]
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x2c): undefined reference to `__imp_getsockname'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x5c): undefined reference to `__imp_ntohs'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream21get_local_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0xa6): undefined reference to `__imp_getnameinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x2c): undefined reference to `__imp_getpeername'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0x5c): undefined reference to `__imp_ntohs'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi[_ZNK7httplib6detail12SocketStream22get_remote_ip_and_portERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi]+0xa6): undefined reference to `__imp_getnameinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail12SocketStream4readEPcy[_ZN7httplib6detail12SocketStream4readEPcy]+0xa0): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail12SocketStream4readEPcy[_ZN7httplib6detail12SocketStream4readEPcy]+0x12f): undefined reference to `__imp_recv'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail12SocketStream4readEPcy[_ZN7httplib6detail12SocketStream4readEPcy]+0x16b): undefined reference to `__imp_recv'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib10ClientImplD0Ev[_ZN7httplib10ClientImplD0Ev]+0x3a): undefined reference to `__imp_shutdown'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib10ClientImplD0Ev[_ZN7httplib10ClientImplD0Ev]+0x4a): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib10ClientImplD1Ev[_ZN7httplib10ClientImplD1Ev]+0x3a): undefined reference to `__imp_shutdown'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib10ClientImplD1Ev[_ZN7httplib10ClientImplD1Ev]+0x4a): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail11select_readEyxx[_ZN7httplib6detail11select_readEyxx]+0x12): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail12select_writeEyxx[_ZN7httplib6detail12select_writeEyxx]+0x12): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZNK7httplib6detail12SocketStream11is_writableEv[_ZNK7httplib6detail12SocketStream11is_writableEv]+0x50): undefined reference to `__imp_recv'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0x84): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0xe6): undefined reference to `__WSAFDIsSet'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0xf5): undefined reference to `__WSAFDIsSet'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail26wait_until_socket_is_readyEyxx[_ZN7httplib6detail26wait_until_socket_is_readyEyxx]+0x12c): undefined reference to `__imp_getsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail6WSInitC1Ev[_ZN7httplib6detail6WSInitC1Ev]+0x1a): undefined reference to `__imp_WSAStartup'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x328): undefined reference to `__imp_getaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x345): undefined reference to `__imp_WSASocketW'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x34c): undefined reference to `__imp_ioctlsocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x3dc): undefined reference to `__imp_connect'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x407): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x4b3): undefined reference to `__imp_freeaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x516): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x542): undefined reference to `__imp_connect'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x550): undefined reference to `__imp_WSAGetLastError'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x56b): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x5d7): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x60a): undefined reference to `__imp_WSAGetLastError'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x625): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x640): undefined reference to `__imp_freeaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x67b): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x694): undefined reference to `__imp_socket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_[_ZN7httplib6detail13create_socketIZNS0_20create_client_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_iibSt8functionIFvyEExxxxxxS9_RNS_5ErrorEEUlyR8addrinfoE_EEyS9_S9_iiibSC_T_]+0x74c): undefined reference to `__imp_socket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6Server24process_and_close_socketEy[_ZN7httplib6Server24process_and_close_socketEy]+0x82): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6Server24process_and_close_socketEy[_ZN7httplib6Server24process_and_close_socketEy]+0xe4): undefined reference to `__imp_shutdown'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/llava_server.o:llava_server.c:(.text$_ZN7httplib6Server24process_and_close_socketEy[_ZN7httplib6Server24process_and_close_socketEy]+0xed): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text+0x3a): undefined reference to `__imp_WSACleanup'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text+0x5248): undefined reference to `__imp_getsockname'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text+0x526f): undefined reference to `__imp_ntohs'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib22default_socket_optionsEy[_ZN7httplib22default_socket_optionsEy]+0xa): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x368): undefined reference to `__imp_getaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x385): undefined reference to `__imp_WSASocketW'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x38c): undefined reference to `__imp_bind'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x393): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x41c): undefined reference to `__imp_listen'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x42f): undefined reference to `__imp_freeaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x6a5): undefined reference to `__imp_freeaddrinfo'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x6e3): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x71b): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_[_ZN7httplib6detail13create_socketIZNKS_6Server20create_server_socketERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiSt8functionIFvyEEEUlyR8addrinfoE_EEySA_SA_iiibSD_T_]+0x734): undefined reference to `__imp_socket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0xed): undefined reference to `__imp_select'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x134): undefined reference to `__imp_accept'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x169): undefined reference to `__imp_setsockopt'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZN7httplib6Server15listen_internalEv[_ZN7httplib6Server15listen_internalEv]+0x4c0): undefined reference to `__imp_closesocket'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZNSt17_Function_handlerIFvvEZN7httplib6Server15listen_internalEvEUlvE0_E9_M_invokeERKSt9_Any_data[_ZNSt17_Function_handlerIFvvEZN7httplib6Server15listen_internalEvEUlvE0_E9_M_invokeERKSt9_Any_data]+0xe2): undefined reference to `__imp_shutdown'
C:/download/w64devkit-1.20.0/w64devkit/bin/ld.exe: obj/web_server.o:web_server.cpp:(.text$_ZNSt17_Function_handlerIFvvEZN7httplib6Server15listen_internalEvEUlvE0_E9_M_invokeERKSt9_Any_data[_ZNSt17_Function_handlerIFvvEZN7httplib6Server15listen_internalEvEUlvE0_E9_M_invokeERKSt9_Any_data]+0xf4): undefined reference to `__imp_closesocket'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.inc:62: bin/llava-server] Error 1
make[1]: Leaving directory 'C:/download/web-rwkv-v0.1.1/llava-cpp-server'
make: *** [Makefile:10: all] Error 2

**Comment by trzy** [comment]
You have to add some flags to the Makefile to build on Windows (wsock2, etc.) If you still need this I can get you the flags.
